# Generated by Django 5.1.6 on 2025-02-27 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subdomains',
            fields=[
                ('domain_name', models.TextField(primary_key=True, serialize=False)),
                ('subdomains', models.TextField()),
            ],
        ),
    ]
